// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHIOvJ-0K2PAO4_4IFzLptEGCBHnZZvR8',
    appId: '1:536784203763:web:cccfaf5ee6e82f35742c86',
    messagingSenderId: '536784203763',
    projectId: 'ur-health-3e147',
    authDomain: 'ur-health-3e147.firebaseapp.com',
    storageBucket: 'ur-health-3e147.firebasestorage.app',
    measurementId: 'G-VCE72X0SET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Vm9sbTaGVETyOTUXyrnUKQBt4FyJK4',
    appId: '1:536784203763:android:63d76e0e6c4dea93742c86',
    messagingSenderId: '536784203763',
    projectId: 'ur-health-3e147',
    storageBucket: 'ur-health-3e147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ya7ESYBlY6A5jIFhbhEvkDkAjZzet80',
    appId: '1:536784203763:ios:b3c38ece06a2cbc6742c86',
    messagingSenderId: '536784203763',
    projectId: 'ur-health-3e147',
    storageBucket: 'ur-health-3e147.firebasestorage.app',
    iosBundleId: 'com.example.urIotApp',
  );
}
